---
- block:
  - name: 'Tap the Caskroom/Cask repository from Github using HTTPS'
    homebrew_tap:
      name: caskroom/cask
      state: present
  rescue: 
  - name: 'Tap the homebrew/cask-versions'
    homebrew_tap:
      name: homebrew/cask-versions
      state: present
