---
- name: "Ensure zsh is already installed"
  stat:
    path: "{{zsh_pref.home}}"
  register: zsh_register

# - name: "Ensure zsh is already installed"
#   command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
#   become: yes

- name: "Download zsh installer"
  get_url:
    url: "https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh"
    dest: /tmp/zsh-installer.sh
    validate_certs: no
    mode: 0775
  when: zsh_register.stat.exists == False

- name: Execute the zsh-installer.sh
  shell: /tmp/zsh-installer.sh
  when: zsh_register.stat.exists == False

- name: Remove the zsh-installer.sh
  file:
    path: /tmp/zsh-installer.sh
    state: absent
  when: zsh_register.stat.exists == False

# - name: "Setup zsh theme"
#   lineinfile:
#     path: "$HOME/.zshrc"
#     path: "$HOME/.zshrc"
#     regexp: '^ZSH_THEME='
#     line: 'ZSH_THEME="awesomepanda"'
#     backrefs: yes

- name: "Fork zsh suggestions"
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: "Fork zsh suggestions"
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: "Setup .zshrc"
  template:
    src: zshrc-template.j2
    dest: "$HOME/.zshrc"

- name: "Set custom TERM for suggestions"
  lineinfile:
    path: /etc/profile.d/zsh-autosuggestions-term.sh
    regexp: '^TERM='
    line: 'TERM=xterm-256color'
    create: yes
  become: yes

- block:
  - name: "Change default shell to zsh"
    shell: chsh -s $(which zsh)
  rescue:
  - name: "Change default shell to zsh"
    shell: chsh -s /bin/zsh

- name: "Informations for help"
  debug:
    msg: "{{item.info}} - {{item.url}}"
  with_items:
    - {info: 'Oh-my-zsh Themes', url: 'https://github.com/robbyrussell/oh-my-zsh/wiki/Themes' }
    - {info: 'Oh-my-zsh Cheat Sheets', url: 'https://github.com/robbyrussell/oh-my-zsh/wiki/Cheatsheet' }
    - {info: 'About zsh-autosuggestions', url: 'https://asciinema.org/a/37390' }
